# Generated by Django 3.2.1 on 2021-10-27 05:10

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('password', models.CharField(max_length=30)),
                ('start', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('end', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('date', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('description', models.TextField()),
                ('room_size', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('price', models.PositiveIntegerField()),
                ('lecture_cnt', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('validation', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onedays.category')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onedays.lecture')),
                ('tutee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tutee')),
            ],
        ),
        migrations.AddField(
            model_name='lecture',
            name='tutees',
            field=models.ManyToManyField(through='onedays.Registration', to='accounts.Tutee'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tutor'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrive_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(default=0)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onedays.registration')),
            ],
        ),
    ]
