# Generated by Django 3.2.1 on 2021-10-29 04:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onedays', '0002_auto_20211028_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='end',
            field=models.TimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='start',
            field=models.TimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
